### ISSUE TITLE
你好，想问下

### ISSUE THREAD

**Issue by zhangxieliu** [wenye123/vue-trip#1]
用cordova怎么打包vue.js写好的代码，并生成apk文件呢

**Comment by wenye123** [comment]
### 创建app ###
	//创建一个命名为firstApp，id为com.cycle.first的app，创建在first文件夹下
	cordova create first com.cycle.firstApp firstApp　-d	

### 添加平台 ###	
	cd first		//进入新创建的文件夹中

	cordova platform add android	//添加一个Android平台

	添加其他平台
	cordova platform add ios
	cordova platform add amazon-fireos
	cordova platform add blackberry10
	cordova platform add firefoxos

	cordova platforms ls		//显示已有的平台

	cordova platform remove android		//删除某个平台
	cordova platform rm android

### 编译app ###
	cordova build			//编译app

	//拆分为两句
	cordova prepare android
	cordova compile android

**Comment by zhangxieliu** [comment]
我试试，非常感谢您

**Comment by dddddd1** [comment]
运行了一下，为啥子是请求程序出错

**Comment by wenye123** [comment]
你是说vue项目 npm run dev的时候吗？没有问题啊，就是一些数据改为我自己填充的，不再是api的数据了

**Comment by dddddd1** [comment]
![222](https://cloud.githubusercontent.com/assets/16111429/23447337/232be6f4-fe85-11e6-8518-641ccf0552f7.png)
![222](https://cloud.githubusercontent.com/assets/16111429/23447340/31bec470-fe85-11e6-8eb9-f4e88f76fd09.png)

**Comment by wenye123** [comment]
不好意思！，我处理好了，你在clone一下吧，谢谢你的提醒
